site_name: Johmathe's doc
theme: readthedocs
site_url: /
site_favicon: img/favicon.png
copyright: Copyleft; 2015, Johan Mathe

pages:
# Introduction:
- ['index.md', 'About', 'Docker']

# Aviation
- ['aviation.md', 'Aviation Links', 'Meh']
